openapi: 3.0.3
info:
  title: User Service API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Listar usuarios
      responses:
        '200':
          description: Lista de usuarios
    post:
      summary: Crear usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '201':
          description: Usuario creado
  /users/{id}:
    get:
      summary: Obtener usuario por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuario encontrado
    put:
      summary: Actualizar usuario
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Usuario actualizado
    delete:
      summary: Eliminar usuario
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Usuario eliminado
  /profile:
    get:
      summary: Obtener perfil del usuario autenticado
      responses:
        '200':
          description: Perfil obtenido
    put:
      summary: Actualizar perfil del usuario autenticado
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileRequest'
      responses:
        '200':
          description: Perfil actualizado
  /preferences:
    get:
      summary: Obtener preferencias del usuario
      responses:
        '200':
          description: Preferencias obtenidas
    put:
      summary: Actualizar preferencias del usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PreferencesRequest'
      responses:
        '200':
          description: Preferencias actualizadas
components:
  schemas:
    UserRequest:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string
      required:
        - email
        - name
        - password
    ProfileRequest:
      type: object
      properties:
        name:
          type: string
        avatar:
          type: string
      required:
        - name
    PreferencesRequest:
      type: object
      properties:
        language:
          type: string
        notifications:
          type: boolean
      required:
        - language
        - notifications
