{
 "title": "Auth Service · Negocio y SLO",
 "tags": [
  "auth-service",
  "slo"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(auth_login_success_total, environment)"
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": "label_values(auth_login_success_total, tenant_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Login success ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(auth_login_success_total{environment=~\"$environment\",tenant_id=~\"$tenant\"}[5m]) / (rate(auth_login_success_total{environment=~\"$environment\",tenant_id=~\"$tenant\"}[5m]) + rate(auth_login_fail_total{environment=~\"$environment\",tenant_id=~\"$tenant\"}[5m]))",
     "legendFormat": "Success ratio"
    }
   ]
  },
  {
   "title": "Latency p95 /login",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(auth_http_request_duration_seconds_bucket{route=\"/login\",environment=~\"$environment\",tenant_id=~\"$tenant\"}[5m])) by (le)) * 1000",
     "legendFormat": "p95 /login"
    }
   ]
  },
  {
   "title": "Token revocations & reuse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(auth_refresh_reuse_blocked_total{environment=~\"$environment\",tenant_id=~\"$tenant\"}[5m])",
     "legendFormat": "Blocked reuse"
    },
    {
     "expr": "rate(auth_token_revoked_total{environment=~\"$environment\",type=\"access\",tenant_id=~\"$tenant\"}[5m])",
     "legendFormat": "Access revoked"
    },
    {
     "expr": "rate(auth_token_revoked_total{environment=~\"$environment\",type=\"refresh\",tenant_id=~\"$tenant\"}[5m])",
     "legendFormat": "Refresh revoked"
    }
   ]
  },
  { "title": "Trace duration (average)", "type": "tempo-topology", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 } }
 ]
}