openapi: 3.0.3
info:
  title: Auth Service API
  version: 1.0.0
paths:
  /register:
    post:
      summary: Registro de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Usuario registrado
  /login:
    post:
      summary: Login de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login exitoso
  /logout:
    post:
      summary: Logout de usuario
      responses:
        '204':
          description: Logout exitoso
  /forgot-password:
    post:
      summary: Solicitud de recuperaci칩n de contrase침a
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
      responses:
        '200':
          description: Email enviado
  /reset-password:
    post:
      summary: Reset de contrase침a
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '200':
          description: Contrase침a actualizada
  /roles:
    get:
      summary: Listado de roles
      responses:
        '200':
          description: Lista de roles
  /permissions:
    get:
      summary: Listado de permisos
      responses:
        '200':
          description: Lista de permisos
components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        name:
          type: string
      required:
        - email
        - password
        - name
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    ForgotPasswordRequest:
      type: object
      properties:
        email:
          type: string
      required:
        - email
    ResetPasswordRequest:
      type: object
      properties:
        token:
          type: string
        newPassword:
          type: string
      required:
        - token
        - newPassword
