name: Lint Markdown Docs

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint.json'
  push:
    paths:
      - '**/*.md'
      - '.markdownlint.json'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: Run markdownlint
        run: markdownlint "**/*.md" --config .markdownlint.json
