name: jwks-rotate-manual

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment (staging|production|dev)"
        required: true
        default: dev

jobs:
  rotate:
    name: Rotate JWKS (manual)
    runs-on: ubuntu-latest
    env:
      SERVICE_DIR: apps/services/auth-service
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: ${{ env.SERVICE_DIR }}/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.SERVICE_DIR }}
      - name: Run rotation job
        env:
          AUTH_LOG_LEVEL: warn
          # TODO: Configurar credenciales de DB via environment/protected vars
        run: npm run jwks:rotate
        working-directory: ${{ env.SERVICE_DIR }}
      - name: Print note
        run: echo "Rotation executed. Validate metrics and JWKS exposure before closing run."
